import mongoose from 'mongoose';

// Generated by https://quicktype.io

export interface Comment {
  _id: ID;
  favoriteCount: number;
  favoritedBy: string[];
  post: ID;
  content: string;
  author: ID;
  createdAt: AtedAt;
  updatedAt: AtedAt;
  __v: number;
}

export interface ID {
  $oid: string;
}

export interface AtedAt {
  $date: string;
}

// 定义笔记的数据库模式
const CommentSchema = new mongoose.Schema<Comment>(
  {
    // 被评论的文章的 id
    post: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Note',
      require: true,
    },
    content: {
      type: String,
      require: true,
    },
    // 创建评论的用户
    author: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      require: true,
    },
    favoriteCount: {
      type: Number,
      default: 0,
    },
    favoritedBy: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
      },
    ],
  },
  {
    // 添加 Date 类型的 createAt 和 updateAt 字段
    timestamps: true,
  }
);

// 通过模式定义 Note 模型
const Comment = mongoose.model<Comment>('Comment', CommentSchema);

export default Comment;
